import { Nav } from '@/components/Nav'
import './globals.css'

type Params = {
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  params?: Params
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        <Nav key="navbar" />
        {'PATH'}
        {children}
      </body>
    </html>
  )
}
